"use client";
import {useEffect,useMemo,useRef,useState} from "react";
type Candle={t:number;o:number;h:number;l:number;c:number;v:number}; type Result={symbol:string;name?:string;exchange?:string;type?:string};
const quick:Result[]=[{symbol:"BTCUSDT",name:"Bitcoin / USDT",exchange:"BINANCE",type:"CRYPTO"},{symbol:"ETHUSDT",name:"Ethereum / USDT",exchange:"BINANCE",type:"CRYPTO"},{symbol:"EURUSD=X",name:"EUR / USD",exchange:"GLOBAL",type:"FOREX"},{symbol:"GBPUSD=X",name:"GBP / USD",exchange:"GLOBAL",type:"FOREX"},{symbol:"GC=F",name:"Gold",exchange:"GLOBAL",type:"COMMODITY"},{symbol:"CL=F",name:"Crude Oil",exchange:"GLOBAL",type:"COMMODITY"},{symbol:"^GSPC",name:"S&P 500",exchange:"US",type:"INDEX"},{symbol:"^NDX",name:"Nasdaq 100",exchange:"US",type:"INDEX"}];
function fmt(n:number|undefined){return n==null||!Number.isFinite(n)?"—":n.toLocaleString(undefined,{maximumFractionDigits:8})}
function Chart({data}:{data:Candle[]}){const pts=useMemo(()=>{if(!data.length)return"";const lo=Math.min(...data.map(x=>x.l)),hi=Math.max(...data.map(x=>x.h)),span=Math.max(hi-lo,1e-9);return data.map((x,i)=>`${(i/(data.length-1))*900},${330-((x.c-lo)/span)*300}`).join(" ")},[data]);return <svg viewBox="0 0 900 340" preserveAspectRatio="none"><polyline fill="none" stroke="currentColor" strokeWidth="3" points={pts}/></svg>}
export default function Home(){
 const [symbol,setSymbol]=useState("BTCUSDT"),[query,setQuery]=useState("BTCUSDT"),[interval,setInterval]=useState("1h"),[data,setData]=useState<Candle[]>([]),[analysis,setAnalysis]=useState<any>(null),[mtf,setMtf]=useState<any>(null),[news,setNews]=useState<any[]>([]),[provider,setProvider]=useState(""),[results,setResults]=useState<Result[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[image,setImage]=useState(""),[imageName,setImageName]=useState(""),fileRef=useRef<HTMLInputElement>(null);
 async function search(q:string){setQuery(q);if(q.trim().length<2){setResults([]);return}try{const r=await fetch("/api/search?q="+encodeURIComponent(q),{cache:"no-store"});const j=await r.json();setResults(j.results||[])}catch{setResults([])}}
 async function load(s:string,tf=interval){setLoading(true);setError("");setAnalysis(null);try{const r=await fetch("/api/market?symbol="+encodeURIComponent(s)+"&interval="+tf+"&limit=300",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.reason||"DATA UNAVAILABLE");setData(j.candles||[]);setProvider(j.provider||"");setSymbol(j.symbol||s);const a=await fetch("/api/analyze",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({candles:j.candles||[],symbol:j.symbol||s,interval:tf})});const aj=await a.json();if(!a.ok)throw new Error(aj.error||"Analysis failed");setAnalysis(aj);const mr=await fetch("/api/multi?symbol="+encodeURIComponent(j.symbol||s),{cache:"no-store"});setMtf(mr.ok?await mr.json():null);const n=await fetch("/api/news?q="+encodeURIComponent(j.symbol||s),{cache:"no-store"});const nj=await n.json();setNews(nj.items||[])}catch(e:any){setData([]);setError("DATA UNAVAILABLE / NO TRADE — "+(e&&e.message?e.message:"verified provider unavailable"))}finally{setLoading(false)}}
 useEffect(()=>{load("BTCUSDT")},[]);
 useEffect(()=>{const id=setInterval(()=>{if(symbol)load(symbol)},60000);return()=>clearInterval(id)},[symbol,interval]);
 const decision=analysis&&analysis.signal?analysis.signal:"WAIT";
 function choose(r:Result){setSymbol(r.symbol);setQuery(r.symbol);setResults([]);load(r.symbol)}
 function onFile(e:any){const f=e&&e.target&&e.target.files?e.target.files[0]:null;if(!f)return;if(f.size>15*1024*1024){setError("CHART IMAGE TOO LARGE — choose a photo under 15 MB.");return}if(!/^image\//.test(f.type)){setError("PLEASE CHOOSE A PHOTO OR IMAGE.");return}if(image)URL.revokeObjectURL(image);setImage(URL.createObjectURL(f));setImageName(f.name)}
 return <div className="app"><header><div className="brand"><b>◉</b><span>SENTINEL<strong> AI</strong></span></div><div className="live">● LIVE GLOBAL MARKETS</div><button className="upload" onClick={()=>fileRef.current&&fileRef.current.click()}>＋ Photos / Camera</button></header><main>
 <section className="hero"><small>MARKET INTELLIGENCE / VERIFIED DATA</small><h1>See the market.<br/><i>Understand the call.</i></h1><p>Live market data, multi-factor analysis, plain-English reasoning, and phone photo upload. The system refuses to invent data or pretend a chart image was analyzed when a verified vision engine is not connected.</p><div className="search"><span>⌕</span><input value={query} onChange={e=>search(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&query.trim())choose({symbol:query.trim().toUpperCase()})}} placeholder="Search BTC, EUR/USD, Apple, Gold, Nasdaq…"/><small>{results.length?"SELECT":"SEARCH"}</small>{results.length>0&&<div className="results">{results.map((r,i)=><button key={r.symbol+i} onClick={()=>choose(r)}><b>{r.symbol}</b><span>{r.name}</span><em>{r.exchange||"GLOBAL"} · {r.type||"MARKET"}</em></button>)}</div>}</div><div className="quick">{quick.map(r=><button key={r.symbol} className={symbol===r.symbol?"sel":""} onClick={()=>choose(r)}>{r.symbol}</button>)}</div></section>
 <section className="market"><div><small>CONNECTED MARKET</small><h2>{symbol}</h2><span>{provider||"Awaiting verified provider"} · ●</span></div><div className="price">{fmt(analysis&&analysis.price)} <small>LIVE</small></div><div className="frames">{["1m","5m","15m","1h","4h","1d"].map(x=><button key={x} className={interval===x?"on":""} onClick={()=>{setInterval(x);load(symbol,x)}}>{x}</button>)}</div><button className="analyze" onClick={()=>load(symbol)} disabled={loading}>{loading?"ANALYZING…":"ANALYZE ↗"}</button></section>
 <section className="grid"><aside><div className="panel"><small>DISCOVER / LIVE</small>{quick.map(r=><button className={symbol===r.symbol?"row active":"row"} key={r.symbol} onClick={()=>choose(r)}><b>{r.symbol}</b><span>{r.name}</span></button>)}<p className="tiny">Coverage is provider-driven. Search returns instruments exposed by connected public providers; unsupported symbols return NO TRADE.</p></div>
 <div className="panel scanner"><small>CHART PHOTO / SCANNER</small><h3>Use a photo from your phone.</h3><p>Choose a screenshot/photo from your gallery, or take a new photo. The image stays in this browser.</p><div className="scanButtons"><button onClick={()=>fileRef.current&&fileRef.current.click()}>CHOOSE FROM PHOTOS</button><button onClick={()=>{if(fileRef.current){fileRef.current.value="";fileRef.current.setAttribute("capture","environment");fileRef.current.click()}}}>TAKE PHOTO</button></div>{image&&<div className="preview"><img src={image} alt="Uploaded trading chart"/><b>{imageName}</b><p>Image received. For a real chart decision, select the exact market above so the engine can verify it against live data.</p><button onClick={()=>{URL.revokeObjectURL(image);setImage("");setImageName("")}}>Remove photo</button></div>}</div></aside>
 <div className="center"><div className="chartCard"><div className="chartHead"><div><small>PRICE ACTION</small><b>{symbol} · {interval}</b></div><span>{analysis&&analysis.freshness==="FRESH"?"● FRESH VERIFIED DATA":"● PROVIDER DATA"}</span></div><div className="chart">{data.length>0?<Chart data={data}/>:<div className="empty">{loading?"Connecting to verified market…":"Search a market to load its live chart."}</div>}</div><div className="foot"><span>◉ VERIFIED LIVE DATA</span><span>{data.length} candles</span><span>{provider||"—"}</span></div></div>
 <div className="metrics">{[["EMA 12",analysis&&analysis.indicators&&analysis.indicators.ema12],["EMA 26",analysis&&analysis.indicators&&analysis.indicators.ema26],["RSI 14",analysis&&analysis.indicators&&analysis.indicators.rsi],["VOL ×",analysis&&analysis.indicators&&analysis.indicators.volumeRatio]].map((m:any)=><div key={m[0]}><small>{m[0]}</small><b>{fmt(m[1])}</b></div>)}</div></div>
 <aside><div className="panel decision"><small>SENTINEL DECISION</small><div className={"signal "+decision.toLowerCase().replace(/ /g,"-")}>{loading?"ANALYZING…":decision}</div><div className="confidence"><b>{analysis&&analysis.confidence!=null?analysis.confidence:"—"}%</b><span>evidence confidence</span></div>{analysis?.ml&&<div className="modelBadge">CALIBRATED MODEL {Math.round((analysis.ml.probability||.5)*100)}% · {analysis.ml.validationAccuracy!=null?Math.round(analysis.ml.validationAccuracy*100)+"% holdout-like validation":""}</div>}<div className="decisionMeta"><span>{analysis&&analysis.trend||"—"} TREND</span><span>{analysis&&analysis.regime||"—"}</span><span>{analysis?analysis.agreement+"/6 checks agree":"—"}</span></div><div className="meter"><i style={{width:(analysis&&analysis.confidence?analysis.confidence:0)+"%"}}/></div>
 <div className="simple"><small>WHY?</small>{(analysis&&analysis.plainEnglish?analysis.plainEnglish:["Load verified market data first."]).slice(0,6).map((x:string,i:number)=><p key={i}>✓ {x}</p>)}</div>
 <div className="levels"><small>KEY LEVELS</small><p>Support <b>{fmt(analysis&&analysis.levels&&analysis.levels.support)}</b></p><p>Resistance <b>{fmt(analysis&&analysis.levels&&analysis.levels.resistance)}</b></p><p>Risk stop <b>{fmt(analysis&&analysis.levels&&analysis.levels.stop)}</b></p><p>Target 1 <b>{fmt(analysis&&analysis.levels&&analysis.levels.target1)}</b></p></div>
 <details><summary>Technical evidence</summary>{(analysis&&analysis.reasons||[]).map((x:string,i:number)=><p key={i}>• {x}</p>)}</details>
 <div className="guard"><b>NO GUARANTEE</b><span>This is evidence, not certainty. The platform never promises profits.</span></div></div></aside></section>
 <section className="mtf"><div><small>MULTI-TIMEFRAME CONSENSUS</small><h2>{mtf?.consensus||"—"}</h2><p>Independent verified 1h / 4h / 1d checks. Missing data never counts as agreement.</p></div>{(mtf?.timeframes||[]).map((x:any)=><div className="tfCard" key={x.interval}><small>{x.interval}</small><b>{x.signal||x.status}</b><span>{x.confidence!=null?x.confidence+"%":""} {x.trend||""}</span>{x.ml&&<em>ML {Math.round((x.ml.probability||.5)*100)}%</em>}</div>)}</section>
 <section className="news"><div><small>MARKET INTELLIGENCE</small><h2>Latest headlines</h2></div>{news.length>0?news.slice(0,6).map((n,i)=><a key={i} href={n.link} target="_blank" rel="noreferrer">{n.title}<small>{n.pub}</small></a>):<p>News appears after a market is loaded.</p>}</section>{error&&<div className="error">{error}</div>}</main><footer>REAL DATA ONLY · PROVIDER VERIFIED · NO GUARANTEED PROFITS · NO AUTOMATIC EXECUTION</footer><input ref={fileRef} hidden type="file" accept="image/*" capture="environment" onChange={onFile}/></div>
}