export type Candle={t:number;o:number;h:number;l:number;c:number;v:number};
const finite=(n:number)=>Number.isFinite(n)?n:0;
const mean=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const sd=(a:number[])=>{const m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))||0};
const ema=(a:number[],p:number)=>{if(a.length<p)return mean(a);let e=mean(a.slice(0,p)),k=2/(p+1);for(let i=p;i<a.length;i++)e=a[i]*k+e*(1-k);return e};
const rsi=(a:number[],p=14)=>{if(a.length<p+1)return 50;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){const d=a[i]-a[i-1];if(d>0)g+=d;else l-=d}return l===0?100:100-100/(1+(g/p)/(l/p))};
const atr=(c:Candle[],p=14)=>{if(c.length<p+1)return 0;const x:number[]=[];for(let i=1;i<c.length;i++)x.push(Math.max(c[i].h-c[i].l,Math.abs(c[i].h-c[i-1].c),Math.abs(c[i].l-c[i-1].c)));return mean(x.slice(-p))};
const ret=(a:number[],n:number)=>a.length>n?a[a.length-1]/a[a.length-1-n]-1:0;
const clean=(n:number)=>finite(Number(n.toFixed(6)));
type F={r1:number;r3:number;r6:number;ema12:number;ema26:number;ema50:number;gap:number;rsi:number;vol:number;atrp:number;volat:number;macd:number};
const feat=(c:Candle[],i:number):F=>{const s=c.slice(0,i+1),a=s.map(x=>x.c),last=a.at(-1)||0,e12=ema(a,12),e26=ema(a,26),e50=ema(a,50),aa=atr(s),rs=a.slice(1).map((x,j)=>x/a[j]-1);return{r1:ret(a,1),r3:ret(a,3),r6:ret(a,6),ema12:e12/last-1,ema26:e26/last-1,ema50:e50/last-1,gap:(e12-e26)/last,rsi:rsi(a),vol:mean(s.slice(-10).map(x=>x.v))/(mean(s.slice(-60,-10).map(x=>x.v))||1),atrp:aa/last,volat:sd(rs.slice(-24)),macd:(e12-e26)/last}};
const vec=(f:F)=>[f.r1,f.r3,f.r6,f.ema12,f.ema26,f.ema50,f.gap,(f.rsi-50)/50,f.vol-1,f.atrp,f.volat,f.macd];
const dist=(a:number[],b:number[])=>Math.sqrt(a.reduce((s,x,i)=>{const z=(x-b[i])/(Math.abs(x)+Math.abs(b[i])+.00001);return s+z*z},0));
function analog(c:Candle[],i:number){const cur=vec(feat(c,i)),rows:{d:number;r1:number;r3:number;r6:number}[]=[];const start=Math.max(70,i-1800),end=i-8;for(let j=start;j<=end;j+=3){const f=feat(c,j);rows.push({d:dist(cur,vec(f)),r1:c[j+1].c/c[j].c-1,r3:c[j+3].c/c[j].c-1,r6:c[j+6].c/c[j].c-1})}rows.sort((a,b)=>a.d-b.d);const top=rows.slice(0,Math.min(50,rows.length));const w=top.map(x=>Math.exp(-2*x.d)/(1+x.d)),sw=w.reduce((s,x)=>s+x,0)||1;const E=(k:'r1'|'r3'|'r6')=>top.reduce((s,x,n)=>s+x[k]*w[n],0)/sw;const e1=E('r1'),e3=E('r3'),e6=E('r6');return{e1,e3,e6,agree:[e1,e3,e6].filter(x=>Math.sign(x)===Math.sign(e1)&&Math.abs(x)>.0001).length/3,k:top.length}};
export type Decision={signal:"STRONG BUY"|"BUY"|"WAIT"|"SELL"|"STRONG SELL"|"NO TRADE";confidence:number;score:number;agreement:number;maxAgreement:number;trend:"UP"|"DOWN"|"MIXED";regime:"TREND"|"RANGE"|"HIGH VOLATILITY";reasons:string[];plainEnglish:string[];freshness:"FRESH"|"STALE";price:number;levels:{support:number;resistance:number;stop:number;target1:number;target2:number};indicators:Record<string,number>};
export function decide(raw:Candle[],interval="1h"):Decision{const c=raw.filter(x=>[x.o,x.h,x.l,x.c,x.v].every(Number.isFinite));if(c.length<220)throw Error("Not enough verified market data.");const a=c.map(x=>x.c),last=a.at(-1)!;const e12=ema(a,12),e26=ema(a,26),e50=ema(a,50),e200=ema(a,200),rs=rsi(a),aa=atr(c),macd=(e12-e26)/last,prev=(ema(a.slice(0,-1),12)-ema(a.slice(0,-1),26))/a.at(-2)!,mom=ret(a,8),vol=mean(c.slice(-10).map(x=>x.v))/(mean(c.slice(-60,-10).map(x=>x.v))||1),volat=sd(a.slice(1).map((x,i)=>x/a[i]-1).slice(-24)),an=analog(c,c.length-1);
const intervalMs:Record<string,number>={"1m":60000,"5m":300000,"15m":900000,"1h":3600000,"4h":14400000,"1d":86400000};const candleMs=intervalMs[interval]||3600000;const age=Math.max(0,Date.now()-c.at(-1)!.t),fresh=age<=candleMs*1.5;
const trend:Decision["trend"]=last>=e50&&e50>=e200?"UP":last<=e50&&e50<=e200?"DOWN":"MIXED";const regime:Decision["regime"]=volat>.012?"HIGH VOLATILITY":Math.abs(mom)<.0015&&Math.abs(macd)<.001?"RANGE":"TREND";
let score=0,agree=0,reasons:string[]=[],plain:string[]=[];const add=(d:number,r:string,p:string)=>{score+=d;agree+=d?1:0;reasons.push(r);plain.push(p)};
add(last>e50?1:-1,last>e50?"Price is above EMA 50.":"Price is below EMA 50.",last>e50?"Buyers have medium-term control.":"Sellers have medium-term control.");
add(e12>e26?2:-2,e12>e26?"EMA 12 is above EMA 26.":"EMA 12 is below EMA 26.",e12>e26?"Short-term trend is up.":"Short-term trend is down.");
add(macd>=prev?1.5:-1.5,macd>=prev?"MACD is rising.":"MACD is falling.",macd>=prev?"Momentum is improving.":"Momentum is weakening.");
add(rs>=52&&rs<=70?1:rs<=48&&rs>=30?-1:0,rs>=52&&rs<=70?"RSI supports upside.":rs<=48&&rs>=30?"RSI supports downside.":"RSI is not directional.",rs>=52&&rs<=70?"Momentum is positive without being extreme.":rs<=48&&rs>=30?"Momentum is negative without being extreme.":"RSI alone is inconclusive.");
add(mom>.0015?1.2:mom<-.0015?-1.2:0,mom>.0015?"Recent momentum is positive.":mom<-.0015?"Recent momentum is negative.":"Recent momentum is mixed.",mom>.0015?"Price has been rising.":mom<-.0015?"Price has been falling.":"Recent price movement is mixed.");
add(an.e1>.00015?3:an.e1<-.00015?-3:0,an.e1>.00015?"Historical analogs lean upward.":an.e1<-.00015?"Historical analogs lean downward.":"Historical analogs show no clear edge.",an.e1>.00015?"Similar past conditions leaned higher.":an.e1<-.00015?"Similar past conditions leaned lower.":"Similar past conditions were mixed.");
if(vol>1.15){reasons.push("Trading activity is above its recent baseline.");plain.push("Higher activity confirms the move.");}
if(regime==="HIGH VOLATILITY"){reasons.push("Volatility is high.");plain.push("Fast markets require more selectivity.");}
if(!fresh)return{signal:"NO TRADE",confidence:0,score:clean(score),agreement:agree,maxAgreement:6,trend,regime,reasons:["The newest candle is stale for this timeframe."],plainEnglish:["The data is too old, so I refuse to force a trade."],freshness:"STALE",price:last,levels:{support:last-aa,resistance:last+aa,stop:last,target1:last,target2:last},indicators:{ema12:clean(e12),ema26:clean(e26),ema50:clean(e50),ema200:clean(e200),rsi:clean(rs),atr:clean(aa),macd:clean(macd),momentum:clean(mom),volumeRatio:clean(vol),volatility:clean(volat),knnEdge:clean(an.e1),knnAgreement:clean(an.agree)}};
const directional=Math.sign(an.e1)===Math.sign(an.e3)&&Math.abs(an.e1)>.0001&&Math.abs(an.e3)>.0001;const supportive6=Math.sign(an.e6)===Math.sign(an.e1)||Math.abs(an.e6)<.0001;const multi=directional&&supportive6;const costFloor=.0004;const strong=Math.abs(score)>=6&&agree>=3&&an.agree>=.667&&Math.abs(an.e1)>costFloor&&multi&&regime!=="RANGE";const normal=Math.abs(score)>=2.5&&agree>=2&&an.agree>=.333&&Math.abs(an.e1)>costFloor;let signal:Decision["signal"]="WAIT";if(strong)signal=score>0?"STRONG BUY":"STRONG SELL";else if(normal)signal=score>0?"BUY":"SELL";const confidence=signal==="WAIT"?Math.max(0,Math.round(50+Math.abs(score)*4+an.agree*8)):Math.min(95,Math.round(55+Math.abs(score)*4+an.agree*12-(regime==="HIGH VOLATILITY"?12:0)));const support=Math.min(...c.slice(-30).map(x=>x.l)),resistance=Math.max(...c.slice(-30).map(x=>x.h)),risk=aa*1.5,dir=score>=0?1:-1;return{signal,confidence,score:clean(score),agreement:agree,maxAgreement:6,trend,regime,reasons:reasons.slice(0,8),plainEnglish:plain.filter(Boolean).slice(0,8),freshness:"FRESH",price:last,levels:{support:clean(support),resistance:clean(resistance),stop:clean(last-dir*risk),target1:clean(last+dir*risk*1.5),target2:clean(last+dir*risk*2.5)},indicators:{ema12:clean(e12),ema26:clean(e26),ema50:clean(e50),ema200:clean(e200),rsi:clean(rs),atr:clean(aa),macd:clean(macd),momentum:clean(mom),volumeRatio:clean(vol),volatility:clean(volat),knnEdge:clean(an.e1),knnAgreement:clean(an.agree)}}}